channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - matplotlib>=3.3,<3.4
      - psutil>=5.8,<5.9
      - tqdm>=4.59,<4.60
      - pandas>=1.1,<1.2
      - scipy>=1.5,<1.6
      - numpy>=1.10,<1.20
      - ipykernel~=6.0
      - azureml-core==1.43.0
      - azureml-defaults==1.43.0
      - azureml-mlflow==1.43.0.post1
      - azureml-telemetry==1.43.0
      - scikit-learn==0.24.1
      - azure-ai-ml