name: mlops-qa-ci-pipeline-$(rev:r)

trigger:
  none

# pr: # PRトリガーはAzure Reposの場合、branch policyで実装します。https://docs.microsoft.com/ja-jp/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers
  # branches:
  #   include:
  #     - 'main'
  #     - 'release/*'


variables:
  - name: AZURE_RESOURCE_MANAGER_CONNECTION_NAME
    value: "azure-devops-service-connection" # Update to '{yourResourceManagerConnectionName}'
  - template: ../mlops/config-mlops.yml
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../mlops/config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
      # 'develop' or feature branches: DEV environment
      - template: ../mlops/config-infra-dev.yml

stages:
  - stage: UnitTest
    displayName: "UnitTest"
    # condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    jobs:
      - template: templates/jobs/run-code-tests.template.yml